repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
        args: [--line-length=120]

  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: flake8
        args: ["--ignore=E501,W503"]
      - id: check-json
      - id: check-yaml
      - id: forbid-new-submodules
